#!/bin/bash
# pgbouncer-setup.sh — front PostgreSQL with a PgBouncer connection pooler for
# RemotePower. Worth it when per-request Postgres connection setup becomes the
# ceiling at high scale (the CGI model opens a fresh connection per request).
# Run it on each app node (PgBouncer on localhost) or on a dedicated pooler host.
#
# RemotePower's Postgres driver disables server-side prepared statements
# (prepare_threshold=None), so **transaction pooling** — the most efficient
# mode — works correctly. Its locks are pg_advisory_XACT locks (released at
# COMMIT), which are also transaction-pooling-safe.
#
# Usage:
#   sudo RP_DB_PASS='…' bash packaging/pgbouncer-setup.sh --install
#   sudo RP_DB_PASS='…' PG_HOST=10.0.0.4 bash packaging/pgbouncer-setup.sh
#   sudo RP_DB_PASS='…' PG_HOST=pg-primary,pg-standby bash packaging/pgbouncer-setup.sh  # HA upstream
#
# Env:
#   RP_DB_PASS    password for the RemotePower role            (required)
#   RP_DB_USER    role name                                    (default: rp)
#   RP_DB_NAME    database name                                (default: remotepower)
#   PG_HOST       upstream Postgres host (or comma-list for HA)(default: localhost)
#   PG_PORT       upstream Postgres port                       (default: 5432)
#   LISTEN_PORT   port PgBouncer listens on                    (default: 6432)
#   POOL_MODE     transaction | session                        (default: transaction)
#   PG_SSLMODE    sslmode to the upstream (require/verify-full)(default: prefer)
#   --install     apt-install pgbouncer if absent

set -euo pipefail

RP_DB_USER="${RP_DB_USER:-rp}"
RP_DB_NAME="${RP_DB_NAME:-remotepower}"
RP_DB_PASS="${RP_DB_PASS:-}"
PG_HOST="${PG_HOST:-localhost}"
PG_PORT="${PG_PORT:-5432}"
LISTEN_PORT="${LISTEN_PORT:-6432}"
POOL_MODE="${POOL_MODE:-transaction}"
PG_SSLMODE="${PG_SSLMODE:-prefer}"
DO_INSTALL=0
[ "${1:-}" = "--install" ] && DO_INSTALL=1

if [ "$(id -u)" -ne 0 ]; then echo "run as root (sudo)" >&2; exit 1; fi
[ -n "$RP_DB_PASS" ] || { echo "set RP_DB_PASS=<RemotePower role password>" >&2; exit 2; }
log() { printf '\033[1;36m==>\033[0m %s\n' "$*"; }

if ! command -v pgbouncer >/dev/null 2>&1; then
  if [ "$DO_INSTALL" -eq 1 ]; then
    log "Installing PgBouncer…"
    apt-get update -qq
    DEBIAN_FRONTEND=noninteractive apt-get install -y pgbouncer
  else
    echo "pgbouncer not installed — re-run with --install." >&2; exit 1
  fi
fi

ETC=/etc/pgbouncer
mkdir -p "$ETC"

# ── userlist (plaintext password, 0600 — PgBouncer uses it for scram auth) ──────
log "Writing ${ETC}/userlist.txt (0600)."
printf '"%s" "%s"\n' "$RP_DB_USER" "$RP_DB_PASS" > "$ETC/userlist.txt"
chown root:postgres "$ETC/userlist.txt" 2>/dev/null || true
chmod 640 "$ETC/userlist.txt"

# ── pgbouncer.ini ───────────────────────────────────────────────────────────────
log "Writing ${ETC}/pgbouncer.ini  (pool_mode=${POOL_MODE}, upstream ${PG_HOST}:${PG_PORT})."
cat > "$ETC/pgbouncer.ini" <<EOF
;; RemotePower PgBouncer — generated by pgbouncer-setup.sh
[databases]
${RP_DB_NAME} = host=${PG_HOST} port=${PG_PORT} dbname=${RP_DB_NAME} sslmode=${PG_SSLMODE}

[pgbouncer]
listen_addr = 127.0.0.1
listen_port = ${LISTEN_PORT}
auth_type = scram-sha-256
auth_file = ${ETC}/userlist.txt
;; transaction pooling is safe: RemotePower disables prepared statements and
;; uses only xact-scoped advisory locks.
pool_mode = ${POOL_MODE}
max_client_conn = 5000
default_pool_size = 25
min_pool_size = 5
reserve_pool_size = 5
server_login_retry = 2
;; many short-lived server conns are cheap; recycle idle ones
server_idle_timeout = 120
logfile = /var/log/pgbouncer/pgbouncer.log
pidfile = /run/pgbouncer/pgbouncer.pid
admin_users = ${RP_DB_USER}
EOF

mkdir -p /var/log/pgbouncer /run/pgbouncer
chown -R postgres:postgres /var/log/pgbouncer /run/pgbouncer 2>/dev/null || true

systemctl enable --now pgbouncer >/dev/null 2>&1 || systemctl restart pgbouncer || true

echo
log "PgBouncer is fronting Postgres on 127.0.0.1:${LISTEN_PORT} (${POOL_MODE} pooling)."
echo "   Point RemotePower at PgBouncer instead of Postgres directly:"
echo "     RP_PG_DSN=postgresql://${RP_DB_USER}:****@127.0.0.1:${LISTEN_PORT}/${RP_DB_NAME}"
echo "   (or the storage marker's \"dsn\"). PgBouncer then handles the upstream"
echo "   connection(s) — for HA set PG_HOST=pg-primary,pg-standby above so the"
echo "   pooler follows a failover."
echo
echo "   NOTE: 127.0.0.1 keeps the pooler local to this app node. If you run a"
echo "   central pooler instead, bind it to the app subnet and require TLS."
